on:
  workflow_call

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: ossrh 
          server-username: MAVEN_USERNAME 
          server-password: MAVEN_CENTRAL_TOKEN 
          gpg-private-key: ${{ secrets.OB_MAVEN_GPG_PRIVATE_KEY }} 
          gpg-passphrase: MAVEN_GPG_PASSPHRASE 
      - name: Configure git for GitHub Actions
        run: |
          git config user.name "ayoukhananov"
          git config user.email "ayoukhananov@outbrain.com"
      - name: Checkout with token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0  # Fetch all history for all tags and branches
      - name: Publish to Apache Maven Central
        run: |
          GPG_TTY=$(tty) mvn --batch-mode release:prepare release:perform -DskipSing=false
        env:
          MAVEN_USERNAME: ${{ secrets.OB_MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OB_MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OB_MAVEN_GPG_PASSPHRASE }}
